CC = g++
CPPFLAGS = -O0 -std=c++14 -Wall -Werror -g

COMMON_HEADERS = node.h HuffmanTree.h CoderBase.h 
COMMON_SOURCES = HuffmanTree.cpp

DECODER_HEADERS = Decoder.h 
DECODER_SOURCES = Decoder.cpp

ENCODER_HEADERS = Encoder.h
ENCODER_SOURCES = Encoder.cpp 

.PHONY: all

DECODER_OBJECTS = $(DECODER_SOURCES:.cpp=.o)
	DECODER_EXECUTABLE = decode

ENCODER_OBJECTS = $(ENCODER_SOURCES:.cpp=.o)
	ENCODER_EXECUTABLE = encode

COMMON_OBJECTS = $(COMMON_SOURCES:.cpp=.o)

all: $(DECODER_EXECUTABLE) $(ENCODER_EXECUTABLE)

$(DECODER_EXECUTABLE): $(DECODER_OBJECTS) $(DECODER_HEADERS) $(COMMON_OBJECTS) $(COMMON_HEADERS)
		$(CC) $(DECODER_OBJECTS) $(COMMON_OBJECTS) -o $@


$(ENCODER_EXECUTABLE): $(ENCODER_OBJECTS) $(ENCODER_HEADERS) $(COMMON_OBJECTS) $(COMMON_HEADERS)
		$(CC) $(ENCODER_OBJECTS) $(COMMON_OBJECTS) -o $@

%.o : %.cpp
		$(CC) $(CPPFLAGS) $(DECODER_SOURCES) $(COMMON_SOURCES) $(ENCODER_SOURCES) -c

clean:
		rm -rf $(DECODER_EXECUTABLE) $(ENCODER_EXECUTABLE) $(DECODER_OBJECTS) $(ENCODER_OBJECTS) $(COMMON_OBJECTS)

